name: Deploy Docs
on:
  push:
    tags: ['v*']

concurrency:
  group: docs-${{ github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    uses: michaelglass/MichaelsWackyFsPackageTools/.github/workflows/michaels-wacky-docs.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
